name: publish

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false

permissions:
  contents: read

jobs:
  publish:
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    if: github.repository == 'cashapp/kotlin-editor' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute check
        run: './gradlew check -s'

      - name: Execute buildHealth
        run: './gradlew buildHealth -s'

      - name: Publish artifacts
        run: './gradlew publishToMavenCentral -s --no-configuration-cache'
